title: My sample book
author: Amelia 
logo: foto emi.jpeg

exclude:
  - references.bib
  - "*.ipynb"
  - "_build"

latex:
  latex_documents:
    targetname: book.tex

sphinx:
  config:
    html_static_path: ["_static"]
    html_js_files:
      - custom.js

bibtex_bibfiles:
  - references.bib

repository:
  url: https://github.com/executablebooks/jupyter-book
  path_to_book: docs
  branch: master

html:
  use_issues_button: true
  use_repository_button: true
